In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
data = load_breast_cancer()
X = data.data
Y = data.target

x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.25, stratify=Y, random_state=42
)

print('Training Samples: ', x_train.shape[0])
print('Testing Samples: ', x_test.shape[0])


Training Samples:  426
Testing Samples:  143


In [9]:
models = {
    'Linear':SVC(kernel='linear', C=1.0),
    'Polynomial':SVC(kernel='poly', C=1.0, degree=3),
    'RBF':SVC(kernel='rbf', C=1.0, gamma=0.01)
}

results = {}

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    results[name] = (acc, cm)


for name, (acc, cm) in results.items():
    print(f'\n=== {name} Kernel ===')
    print(f'Accuracy: {acc:.3f}')
    print('Confusion Matrix: ')
    print(cm)


=== Linear Kernel ===
Accuracy: 0.951
Confusion Matrix: 
[[47  6]
 [ 1 89]]

=== Polynomial Kernel ===
Accuracy: 0.916
Confusion Matrix: 
[[43 10]
 [ 2 88]]

=== RBF Kernel ===
Accuracy: 0.629
Confusion Matrix: 
[[ 0 53]
 [ 0 90]]


In [11]:
best_acc = 0
best_C = None

for c in [0.01, 0.1, 1, 10, 20, 50]:
    model = SVC(kernel='linear', C=c)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    acc = accuracy_score(y_test, y_pred)

    print(f'C={c:>4}, Accuracy: {acc:.3f}')

    if acc > best_acc:
        best_acc = acc
        best_C = c

print(f'Best C Seleted: {best_C}')
print(f'Best Accuracy: {best_acc}')

C=0.01, Accuracy: 0.958
C= 0.1, Accuracy: 0.958
C=   1, Accuracy: 0.951
C=  10, Accuracy: 0.951
C=  20, Accuracy: 0.958
C=  50, Accuracy: 0.958
Best C Seleted: 0.01
Best Accuracy: 0.958041958041958
